// <auto-generated />
namespace Core
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dev1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905100400180_dev1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
